#!/bin/sh

CSS=/home/controls/css/CSS_EPICS_3.2.14


mkdir -p $HOME/CSS
LOG=/tmp/css_`date +%Y-%m-%d-%H-%M-%S`.log
#WS=$HOME/CSS/Default
WS=/home/controls/css/workspaces/$USER

# Create combined settings
INI=/tmp/css$$.ini
cat /home/controls/css/settings.ini /home/controls/bldemo/css/settings.ini >$INI

$CSS/css -consoleLog -pluginCustomization $INI -workspace_prompt $WS -share_link /home/controls/bldemo/opi=/bldemo/opi "$@" >$LOG 2>&1  &

