#!/bin/sh
#
# scan_server  Service-type script to control the scan server
#
# This script is copied to /etc/rc.d/init.d
# and registered with /sbin/chkconfig to run as a Linux service
#
# chkconfig: - 80 20
#
# kasemirk@ornl.gov

ALARM_SERVER=/home/controls/css/BEAST/AlarmServer_3.2.16


# Default scan server RMI uses 4810, 4811
# Use 4809 for telnet access
CONSOLE=4809

# Combine global settings with beam-line settings
INI=/tmp/alarm_server.ini
cat /home/controls/css/settings.ini /home/controls/bldemo/css/settings.ini >$INI

ARGS="-console $CONSOLE -data $ALARM_SERVER/workspace -consoleLog -pluginCustomization $INI"
USER=chenxh

unset DISPLAY

function start()
{
	su - $USER -c "nohup $ALARM_SERVER/AlarmServer $ARGS >>$ALARM_SERVER/console.log 2>&1 &"
}

function stop()
{
	echo close | nc localhost $CONSOLE
}

case $1 in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
status)
	ps aux | fgrep AlarmServer | grep -v fgrep
	;;
console)
	telnet localhost $CONSOLE
	;;
*)	echo "Usage: $0 {start|stop|restart|status|console}"
        exit 2
esac

